apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: oddo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: "bitnami_oddo"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: POSTGRESQL_USERNAME
              value: "bn_odoo"
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
      volumes:
        - name: postgres-storage
          emptyDir: {}